<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Real production data imported from a live-site SQL export (u397570845_unlisted_gain1.sql).
 */
class UnlistedStocksSeeder extends Seeder
{
    private const COLUMNS = ['UL_STOCKS_FINCODE', 'UL_STOCKS_COMPNAME', 'UL_STOCKS_SLUG', 'UL_STOCKS_LOGO_LINK', 'UL_STOCKS_IND_CODE', 'UL_STOCKS_INDUSTRY', 'UL_STOCKS_ISIN', 'UL_STOCKS_S_NAME', 'UL_STOCKS_CHAIRMAN', 'UL_STOCKS_MDIR', 'UL_STOCKS_CATEGORY', 'UL_STOCKS_INC_MONTH', 'UL_STOCKS_INC_YEAR', 'UL_STOCKS_STATUS', 'UL_STOCKS_ADD1', 'UL_STOCKS_ADD2', 'UL_STOCKS_ADD3', 'UL_STOCKS_CITY_NAME', 'UL_STOCKS_PINCODE', 'UL_STOCKS_STATE_NAME', 'UL_STOCKS_PHONE', 'UL_STOCKS_FAX_NO', 'UL_STOCKS_WEBSITE', 'UL_STOCKS_E_MAIL', 'UL_STOCKS_ABOUT', 'UL_STOCKS_INSERT_BY', 'UL_STOCKS_INSERT_TIME', 'UL_STOCKS_UPDATE_TIME', 'UL_STOCKS_COMP_RATING', 'UL_STOCKS_VALUATION_RATING', 'UL_STOCKS_LOT_SIZE', 'UL_STOCKS_ROFR_FLAG', 'UL_STOCKS_DEMAT_ACCOUNT_REQ', 'UL_STOCKS_BUY_SELL_FLAG', 'UL_STOCKS_COMPNAME_TYPE', 'UL_STOCKS_Qtr_Data_Publish'];

    private const ROWS = [
        [100001, 'NSE - National Stock Exchange', 'nse-national-stock-exchange', 'images/company-logo/nse-national-stock-exchange.jpg', 51, 'Finance - Stock Broking', 'INE721I01024', 'NSE', null, null, 'pre_ipo', null, '1992', '1', null, null, null, null, null, null, null, null, 'https://www.nseindia.com/', null, 'The National Stock Exchange of India (NSE) is India’s leading stock exchange and one of the world’s largest financial market infrastructure institutions. Established in 1992 and commencing operations in 1994, NSE transformed the Indian capital market by introducing fully automated, screen-based electronic trading. Headquartered in Mumbai, it provides a transparent, efficient, and technology-driven platform for trading across multiple asset classes, including equities, derivatives, currencies, debt instruments, exchange-traded funds, and mutual funds.

NSE is widely recognized for its benchmark indices, particularly the NIFTY 50, which serves as a key indicator of the Indian equity market. The exchange plays a vital role in capital formation, investor participation, and economic growth by facilitating fair and orderly markets. Supported by robust technology, strong risk management systems, and high standards of governance, NSE serves millions of investors, market participants, and institutions. Its continued focus on innovation, market development, and investor protection has strengthened its position as a cornerstone of India’s financial ecosystem.', '1', '2026-06-20 07:14:07', '2026-06-21 04:39:42', '5', '4', '100', 'No', 'Both', 'Yes', 'unlisted', 'Yes'],
        [100002, 'Onix Renewable Limited', 'onix-renewable-limited', 'images/company-logo/onix-renewable-limited.png', 42, 'Engineering', 'INE0TG701015', 'Onix Renewable', null, null, 'pre_ipo', null, '2014', '1', null, null, null, null, null, null, null, null, 'https://onixrenewable.com/', null, 'Onix Renewable Limited is an integrated renewable energy company headquartered in Rajkot, Gujarat, India. Founded in 2007, the company operates across the renewable energy value chain, offering solutions in solar, wind, hybrid power, battery energy storage systems (BESS), power infrastructure, and emerging green fuel technologies. The company provides end-to-end services, including engineering, procurement and construction (EPC), independent power production (IPP), project development, operations and maintenance, and solar module manufacturing.

With a strong presence in utility-scale and commercial renewable energy projects, Onix Renewable has delivered clean energy installations across India. The company focuses on supporting the transition to sustainable energy through innovative technologies, efficient project execution, and integrated energy solutions. Its portfolio includes solar power plants, wind farms, hybrid renewable projects, transmission and distribution infrastructure, and green hydrogen initiatives. Driven by a commitment to sustainability and innovation, Onix Renewable aims to contribute significantly to India’s clean energy transition and long-term energy security goals.', '1', '2026-06-20 09:00:28', '2026-06-21 06:00:50', '4', '5', '1000', 'No', 'Both', 'Yes', 'unlisted', 'Yes'],
        [100003, 'Polymatech Electronics Private Limited', 'polymatech-electronics-private-limited', 'images/company-logo/polymatech-electronics-private-limited.png', null, null, 'INE0OLN01029', 'Polymatech', null, null, 'pre_ipo', null, '2007', '1', null, null, null, null, null, null, null, null, 'https://www.polymatech.sg/', null, 'Polymatech Electronics Limited is a leading semiconductor and opto-electronics manufacturer headquartered in Oragadam, Tamil Nadu, India. Established in 2007, the company has emerged as a significant player in India\'s semiconductor ecosystem, focusing on the design, development, packaging, and manufacturing of advanced semiconductor components and opto-semiconductor products.

The company specializes in compound semiconductor technologies used across diverse applications, including telecommunications, consumer electronics, automotive systems, industrial automation, healthcare devices, and next-generation digital infrastructure. Polymatech is recognized for its emphasis on advanced manufacturing processes, research and development, and high-precision semiconductor packaging solutions.

With state-of-the-art production facilities and a growing international footprint, the company aims to strengthen India\'s position in the global semiconductor value chain while supporting the country\'s vision of technological self-reliance. Polymatech continues to invest in innovation, capacity expansion, and strategic partnerships to address the increasing demand for semiconductor solutions worldwide. Its commitment to quality, technological excellence, and sustainable growth has positioned it as one of India\'s prominent emerging semiconductor companies.', '1', '2026-06-20 09:25:45', '2026-06-21 06:18:15', '5', '4', '1000', 'No', 'Both', 'Yes', 'unlisted', 'Yes'],
        [100004, 'Metropolitan Stock Exchange of India Limited - MSEI', 'metropolitan-stock-exchange-of-india-limited-msei', 'images/company-logo/metropolitan-stock-exchange-of-india-limited-msei.jpg', 157, 'Finance - Others', 'INE312K01010', 'MSEI', null, null, 'pre_ipo', null, '2008', '1', null, null, null, null, null, null, null, null, 'https://mseindia.com/', null, 'Metropolitan Stock Exchange of India Limited (MSE) is a national-level stock exchange in India that provides a technology-driven platform for trading and investment across multiple financial market segments. Established in 2008 and recognized by the Securities and Exchange Board of India (SEBI), the exchange facilitates trading in equities, equity derivatives, currency derivatives, debt instruments, and other capital market products.

Headquartered in Mumbai, MSE is committed to enhancing transparency, efficiency, and accessibility in India’s financial markets through advanced electronic trading infrastructure and robust risk management systems. The exchange serves investors, brokers, corporates, and other market participants by offering a secure and reliable marketplace for capital formation and wealth creation.

MSE is also known for its benchmark index, SX40, which represents leading companies across key sectors of the Indian economy. With a focus on innovation, investor education, market development, and financial inclusion, the exchange aims to expand participation in the capital markets and contribute to the growth and modernization of India’s financial ecosystem.', '1', '2026-06-20 11:52:23', '2026-06-21 06:33:45', '5', '4', '10000', 'No', 'Both', 'Yes', 'unlisted', 'Yes'],
        [100005, 'Oravel Stays Limited - OYO', 'oravel-stays-limited-oyo', 'images/company-logo/oravel-stays-limited-oyo.png', 60, 'Hotel, Resort & Restaurants', 'INE561T01021', 'OYO', null, null, 'pre_ipo', null, '2012', '1', null, null, null, null, null, null, null, null, 'https://www.oyorooms.com/', null, 'Oravel Stays Limited, widely known through its hospitality brand OYO, is one of the world\'s leading travel and accommodation technology companies. Founded in 2013 and headquartered in Gurugram, India, the company operates a digital platform that connects travelers with a diverse network of hotels, homes, resorts, and vacation rentals across multiple countries.

OYO leverages technology, data analytics, and standardized operating practices to help property owners improve occupancy, revenue management, customer experience, and operational efficiency. Its platform enables travelers to discover, book, and manage accommodations through a seamless digital experience while offering affordable and quality lodging options across various travel segments.

Over the years, the company has expanded its presence internationally, serving both leisure and business travelers through a wide portfolio of hospitality offerings. OYO continues to focus on innovation, customer-centric services, and asset-light growth strategies to strengthen its position in the global hospitality industry. The company plays a significant role in the modernization and digitization of the budget and mid-market accommodation sector.', '1', '2026-06-20 12:05:44', '2026-06-21 06:04:32', '5', '5', '1000', 'No', 'Both', 'Yes', 'unlisted', 'Yes'],
        [100006, 'Sunday Proptech Limited - OYO Assets', 'sunday-proptech-limited-oyo-assets', 'images/company-logo/sunday-proptech-limited-oyo-assets.png', 60, 'Hotel, Resort & Restaurants', 'INE1DBV01024', 'OYO Assets', null, null, 'startup_funding', null, '2018', '1', null, null, null, null, null, null, null, null, 'https://www.sundayproptech.com/', null, 'Sunday Proptech Limited (CIN: U55109DL2018PLC331290), incorporated on 21 March 2018 and headquartered in Connaught Place, New Delhi, is an Indian hospitality real estate company backed by the PRISM Group, the parent company of OYO. The company operates as an investment and asset-ownership platform focused on acquiring, developing, and managing premium and mid-premium hospitality assets across India, with plans to expand into select international markets. These properties are operated under PRISM’s hospitality brands, including Sunday Hotels, Palette Hotels, and Townhouse. Its business model centers on long-term ownership and management contracts, enabling the generation of stable rental and operating income while benefiting from capital appreciation. By combining real estate investment with PRISM’s established hospitality brands, technology, and operational expertise, Sunday Proptech aims to build a diversified portfolio of high-quality, income-generating hotel assets in the mid-premium and premium segments.', '6', '2026-07-18 07:44:42', '2026-07-18 08:04:04', '5', '4', '1000', 'No', 'Both', 'Yes', 'unlisted', 'No'],
        [100007, 'GFCL EV Products Limited', 'gfcl-ev-products-limited', 'images/company-logo/gfcl-ev-products-limited.png', 39, 'Electric Equipment', 'INE0KA501014', 'GFCL EV Product LTD', null, null, 'pre_ipo', null, '2021', '1', null, null, null, null, null, null, null, null, 'https://gfclev.co.in/', null, 'GFCL EV Products Limited, a wholly owned subsidiary of Gujarat Fluorochemicals (GFL) and part of the INOXGFL Group, is an Indian conglomerate with over 90 years of expertise in chemicals and renewable energy. The company is a vertically integrated manufacturer of critical intermediate materials for lithium-ion batteries, offering a comprehensive portfolio that includes LiPF and NaPF electrolyte salts, specialized electrolyte additives, electrolyte formulations, LFP cathode active materials, and high-performance polymer binders such as PVDF and PTFE. Positioned to meet the growing global demand for electric vehicles (EVs) and energy storage systems, GFCL EV Products has announced plans to invest approximately ₹6,000 crore (around US$720 million) over the next four to five years to expand its manufacturing capacity to nearly 200 GWh annually. As of December 2023, the company had already committed around ₹650 crore toward this expansion.', '6', '2026-07-18 08:00:14', '2026-07-18 08:03:05', '4', '4', '2500', 'No', 'Both', 'Yes', 'unlisted', 'No'],
        [100008, 'HDFC Securities Limited', 'hdfc-securities-limited', 'images/company-logo/hdfc-securities-limited.png', 51, 'Finance - Stock Broking', 'INE700G01014', 'HDFC Securities', null, null, 'pre_ipo', 'April', '2000', '1', null, null, null, null, null, null, null, null, 'https://www.hdfcsec.com/', null, 'HDFC Securities, established in April 2000, commenced operations as a joint venture between HDFC Limited, Indocean eSecurities Holding Ltd., and HDFC Bank Ltd. Today, it operates as a wholly owned subsidiary of HDFC Bank, one of India\'s leading private sector banks.

The company is a prominent financial services intermediary offering a comprehensive range of investment and wealth management solutions. Its core services include equity and derivatives broking, along with the distribution of financial products such as mutual funds, fixed deposits, insurance, bonds, and other investment instruments. As the stockbroking and distribution arm of the HDFC Group, HDFC Securities serves a customer base of over 2.7 million and is a corporate member of both the Bombay Stock Exchange (BSE) and the National Stock Exchange (NSE).

HDFC Securities has an extensive pan-India presence with more than 216 branches across 159 cities and towns. Complementing its physical network, the company offers a robust digital ecosystem that enables customers to access its services seamlessly through online platforms, mobile applications, telephone-based trading, and branch-assisted channels, providing a convenient and integrated investment experience.', '6', '2026-07-18 08:14:33', '2026-07-18 08:16:05', '5', '5', '5', 'No', 'Both', 'Yes', 'unlisted', 'No'],
        [100009, 'Cochin International Airport Limited', 'cochin-international-airport-limited', 'images/company-logo/cochin-international-airport-limited.jpg', 4, 'Airlines', 'INE02KH01019', 'CIAL', null, null, 'pre_ipo', 'March', '1994', '1', null, null, null, null, null, null, null, null, 'https://cial.aero/', null, 'Cochin International Airport Limited (CIAL), incorporated on 30 March 1994 and headquartered in Kochi, Kerala, is India\'s first greenfield airport developed under a public-private partnership (PPP) model. The Government of Kerala is the largest shareholder, holding approximately 32% of the company\'s equity. CIAL is widely recognized for pioneering sustainable airport operations and became the world\'s first airport to be fully powered by solar energy.

The airport is among India\'s busiest international gateways and has established itself as a leading aviation hub through its focus on operational efficiency, sustainability, and customer service. In addition to passenger and cargo operations, CIAL offers a wide range of services, including duty-free retail, shopping and dining facilities, transportation, security, accommodation, aircraft maintenance and repair (MRO) services, and specialized infrastructure for handling perishable cargo. The company also operates an aviation training institute that provides professional training for pilots, cabin crew, aircraft engineers, technicians, and ground support personnel.

To support its diversified operations, CIAL has established several subsidiaries, including Cochin International Aviation Services Limited, Air Kerala International Services Limited, CIAL Infrastructure Limited, CIAL Duty Free and Retail Services Limited, and Kerala Waterways and Infrastructures Limited, strengthening its presence across aviation, infrastructure, and related service segments.', '6', '2026-07-18 08:30:00', '2026-07-18 08:32:17', '5', '4', '100', 'No', 'Both', 'Yes', 'unlisted', 'No'],
        [100010, 'Orbis Financial Corporation Limited', 'orbis-financial-corporation-limited', 'images/company-logo/orbis-financial-corporation-limited.png', 49, 'Finance - Investment', 'INE155K01013', 'Orbis Financial', null, null, 'pre_ipo', null, '2009', '1', null, null, null, null, null, null, null, null, 'https://www.orbisfinancial.in/', null, 'Orbis Financial Corporation Limited is a leading provider of securities and custodial services in India\'s financial services industry, serving foreign and domestic institutional investors, corporates, high-net-worth individuals (HNIs), brokers, portfolio managers, wealth managers, hedge funds, and private equity funds. Since commencing operations as a custodian in 2009, the company has focused on delivering specialized custody solutions that enable clients to manage their investment operations efficiently, securely, and in compliance with evolving regulatory requirements.

Over the years, Orbis has built a strong reputation in the broker-dealer and institutional investor segments by maintaining a dedicated focus on custodial services. Its business is supported by a robust, state-of-the-art technology platform built on an integrated ERP system, enabling seamless operations, scalability, and the flexibility to adapt products and services to changing client needs. The company further differentiates itself through its highly customized reporting solutions, which provide investors with comprehensive, accurate, and timely information to support effective investment management. Backed by experienced professionals and technology-driven processes, Orbis emphasizes responsive, customer-centric service while delivering efficient, reliable, and cost-effective custodial solutions.', '6', '2026-07-18 08:48:42', '2026-07-18 08:50:28', '5', '5', '100', 'No', 'Both', 'Yes', 'unlisted', 'No'],
        [100011, 'Garuda Aerospace Limited', 'garuda-aerospace-limited', 'images/company-logo/garuda-aerospace-limited.png', 142, 'Other', 'INE0REL01021', 'Garuda Aerospace', null, null, 'pre_ipo', null, '2015', '1', null, null, null, null, null, null, null, null, 'https://www.garudaaerospace.com/', null, 'Garuda Aerospace Limited is an Indian drone technology company headquartered in Chennai, established in 2015 by Agnishwar Jayaprakash and Rithika Mohan. The company specializes in the design, manufacturing, and deployment of unmanned aerial systems (UAS), offering comprehensive Drone-as-a-Service (DaaS) solutions across sectors such as agriculture, industrial operations, infrastructure, enterprise, and defense.

Its product and service portfolio includes precision agriculture drones for crop monitoring and pesticide spraying, industrial inspection and surveillance drones, aerial mapping solutions, and pilot training through a DGCA-approved Remote Pilot Training Organisation (RPTO). By developing cost-effective and technologically advanced drone solutions, Garuda Aerospace enables organizations to enhance operational efficiency, improve safety, and make data-driven decisions.

Over the years, the company has expanded beyond agricultural applications into defense, logistics, disaster management, infrastructure inspection, and public-sector projects. Through strategic collaborations with technology partners, government agencies, and defense organizations, Garuda Aerospace has successfully executed large-scale drone deployments across India, including initiatives supporting disaster relief and pandemic response. As a key participant in India\'s rapidly evolving drone ecosystem, the company is committed to advancing indigenous drone manufacturing and strengthening the country\'s capabilities in next-generation aerial technologies.', '6', '2026-07-18 09:15:21', '2026-07-18 09:16:48', '5', '3', '100', 'No', 'Both', 'Yes', 'unlisted', 'No'],
        [100012, 'Hinduja Leyland Finance Limited', 'hinduja-leyland-finance-limited', 'images/company-logo/hinduja-leyland-finance-limited.png', 50, 'Finance - NBFC', 'INE146O01014', 'Hinduja Leyland Finance', null, null, 'pre_ipo', null, '2008', '1', null, null, null, null, null, null, null, null, 'https://www.hindujaleylandfinance.com/', null, 'Hinduja Leyland Finance Limited (HLFL) is a leading non-banking financial company (NBFC) in India and a part of the Hinduja Group. Established as a joint venture between the Hinduja Group and Ashok Leyland, one of India\'s largest commercial vehicle manufacturers, the company provides a comprehensive range of financing solutions to individuals, small businesses, and corporate customers.

HLFL\'s product portfolio includes commercial and passenger vehicle financing, construction equipment and asset financing, personal loans, business loans, and other retail lending products. The company has built a strong presence across India, with a particular focus on supporting the transportation, logistics, and infrastructure sectors through customized financing solutions.

Driven by a customer-centric approach, HLFL leverages technology and digital platforms to enhance operational efficiency, streamline loan processing, and improve customer experience. With its extensive distribution network and diversified lending portfolio, the company continues to play an important role in expanding access to credit while supporting the growth of India\'s automotive, commercial transport, and infrastructure ecosystems.', '6', '2026-07-18 09:21:42', '2026-07-18 09:24:06', '5', '3', '1000', 'No', 'Both', 'Yes', 'unlisted', 'No'],
        [100013, 'ESDS Software Solution Ltd', 'esds-software-solution-ltd', 'images/company-logo/esds-software-solution-ltd.jpg', 65, 'IT - Software', 'INE0DRI01029', 'ESDS Software', null, null, 'pre_ipo', null, '2005', '0', null, null, null, null, null, null, null, null, 'https://www.esds.co.in/', null, 'ESDS Software Solution Limited (ESDS), founded in 2005 and headquartered in Nashik, India, is a leading provider of cloud computing, managed IT services, and software solutions. The company offers a comprehensive portfolio of services, including Infrastructure-as-a-Service (IaaS), Managed Services, and Software-as-a-Service (SaaS), with its flagship **eNlight Cloud** platform providing scalable cloud infrastructure, community cloud solutions, and cloud-based applications.

Beyond cloud services, ESDS delivers a broad range of technology solutions encompassing artificial intelligence, digital banking, hosted payment platforms, IT infrastructure and cloud hosting, banking software, ATM card management systems, and specialized solutions for the banking and financial services sector. Its offerings also include database administration, IT consulting, application development, email migration, disaster recovery and backup solutions, cross-platform recovery services, SAP HANA hosting, and mobile application hosting.

ESDS serves a diverse client base across industries such as banking and financial services (BFSI), manufacturing, information technology (IT/ITES), telecommunications, real estate, pharmaceuticals, retail, education, and government. With operations spanning approximately 19 countries across the Asia-Pacific, Europe, the Middle East, Africa, and the Americas, the company has established a strong global presence while supporting organizations in their digital transformation and cloud adoption initiatives.', '6', '2026-07-19 10:52:43', '2026-09-02 11:40:44', '4', '3', '100', 'No', 'Both', 'Yes', 'unlisted', 'No'],
        [100014, 'Chennai Super Kings Cricket Limited - CSK', 'chennai-super-kings-cricket-limited-csk', 'images/company-logo/chennai-super-kings-cricket-limited-csk.png', 142, 'Other', 'INE852S01026', 'CSK', null, null, 'pre_ipo', 'December', '2014', '1', null, null, null, null, null, null, null, null, 'https://www.chennaisuperkings.com/', null, 'Chennai Super Kings Cricket Limited (CSKCL), incorporated on 19 December 2014, is the entity that owns and manages the Chennai Super Kings franchise of the Indian Premier League (IPL). A subsidiary of India Cements Limited, the company oversees the commercial, operational, and brand management activities of one of India\'s most successful and widely followed cricket franchises.

The Chennai Super Kings team was established in 2008 and is based in Chennai, Tamil Nadu. Competing in the Indian Premier League, the franchise has built a strong legacy through its consistent performances and loyal fan base. The team plays its home matches at the M.A. Chidambaram Stadium (Chepauk), one of India\'s most iconic cricket venues. Over the years, Chennai Super Kings has emerged as one of the most successful franchises in IPL history, consistently recording one of the highest win percentages in the tournament while securing multiple championship titles, reinforcing its position as a premier brand in Indian sports and entertainment.', '6', '2026-07-19 11:19:18', '2026-07-19 11:21:27', '5', '4', '100', 'No', 'Both', 'Yes', 'unlisted', 'No'],
        [100015, 'API Holdings Ltd - Pharmeasy', 'api-holdings-ltd-pharmeasy', 'images/company-logo/api-holdings-ltd-pharmeasy.jpg', 155, 'e-Commerce', 'INE0DJ201029', 'Pharmeasy', null, null, 'pre_ipo', null, '2019', '1', null, null, null, null, null, null, null, null, 'https://pharmeasy.in/', null, 'API Holdings Limited, incorporated on 31 March 2019, is a leading digital healthcare company in India that develops and operates an integrated healthcare platform through its network of subsidiaries. The company offers a comprehensive ecosystem of healthcare services, combining digital technology with pharmaceutical distribution, diagnostics, and healthcare solutions.

Its flagship consumer platform, **PharmEasy**, enables users to conveniently order prescription medicines, over-the-counter healthcare products, and other wellness essentials with home delivery services. In addition to its healthcare offerings, the company provides a range of business support services, including call center operations, medical and legal transcription, data processing, warehousing, logistics, and database management.

API Holdings has expanded its presence through strategic acquisitions and investments, with a portfolio comprising 26 subsidiaries, including prominent healthcare brands such as Docon and Thyrocare. By integrating pharmacy, diagnostics, teleconsultation, and healthcare technology services, the company aims to improve access to affordable, technology-enabled healthcare solutions across India.', '6', '2026-07-19 11:32:27', '2026-07-19 11:34:04', '5', '4', '5000', 'No', 'Both', 'Yes', 'unlisted', 'No'],
        [100016, 'Hella Infra Market Private Limited', 'hella-infra-market-private-limited', 'images/company-logo/hella-infra-market-private-limited.png', 142, 'Other', 'INE06E501010', 'Hella Infra Market', null, null, 'pre_ipo', null, '2016', '1', null, null, null, null, null, null, null, null, 'https://infra.market/', null, 'Hella Infra Market Limited (operating as Infra.Market), established in 2016 and headquartered in Thane, Maharashtra, is a leading technology-enabled construction materials platform serving both business (B2B) and retail (B2C) customers. The company integrates manufacturing, technology, and supply chain capabilities to provide end-to-end solutions for the construction and infrastructure sectors.

Infra.Market offers a comprehensive portfolio spanning more than 15 product categories, including concrete, steel, aggregates, walling materials, plumbing products, tiles, paints, electricals, sanitaryware, modular kitchens, and other building and lifestyle solutions. In addition to distributing established third-party brands, the company has developed a robust portfolio of proprietary brands through strategic acquisitions and in-house manufacturing, including RDC Concrete, Shalimar Paints, Emcer, Millennium Tiles, Amstrad, IVAS, and INICIO.

Supported by an extensive network of over 250 manufacturing facilities and warehouses across more than 55 cities, Infra.Market emphasizes quality, supply chain efficiency, and timely delivery. By leveraging technology, data-driven procurement, and vertically integrated operations, the company is transforming the traditionally fragmented building materials industry while positioning itself as a comprehensive one-stop solution for construction and infrastructure requirements across India.', '6', '2026-07-19 11:49:46', '2026-07-19 11:51:29', '4', '4', '1', 'No', 'NSDL', 'Yes', 'unlisted', 'No'],
        [100017, 'Motilal Oswal Home Finance Limited', 'motilal-oswal-home-finance-limited', 'images/company-logo/motilal-oswal-home-finance-limited.png', 48, 'Finance - Housing', 'INE658R01011', 'Motilal Oswal', null, null, 'pre_ipo', 'October', '2013', '1', null, null, null, null, null, null, null, null, 'https://motilaloswalhf.com/', null, 'Motilal Oswal Home Finance Limited (MOHFL) is a housing finance company and a part of the Motilal Oswal Group, focused on expanding access to affordable home financing across India. Incorporated in 2013, the company provides a range of mortgage solutions, including home purchase, construction, renovation, extension, and loans against property, primarily catering to low- and middle-income customers. Registered with the Reserve Bank of India as a Housing Finance Company, MOHFL emphasizes responsible lending, robust underwriting practices, and technology-driven operations to deliver a seamless customer experience. The company has built a diversified retail loan portfolio with a strong presence across multiple states through its extensive branch network and sourcing channels. Supported by experienced leadership, sound risk management, and a diversified funding base, MOHFL continues to strengthen its market position while maintaining healthy asset quality. Its customer-centric approach, digital processes, and focus on financial inclusion enable it to support aspiring homeowners and contribute to India\'s growing affordable housing sector.', '6', '2026-07-25 04:54:33', '2026-07-25 04:57:36', '5', '3', '1000', 'No', 'Both', 'Yes', 'unlisted', 'No'],
        [100018, 'National Commodity and Derivatives Exchange Limited - NCDEX', 'national-commodity-and-derivatives-exchange-limited-ncdex', 'images/company-logo/national-commodity-and-derivatives-exchange-limited-ncdex.png', 157, 'Finance - Others', 'INE127G01010', 'NCDEX', null, null, 'pre_ipo', 'April', '2003', '1', null, null, null, null, null, null, null, null, 'https://www.ncdex.com/', null, 'National Commodity and Derivatives Exchange Limited (NCDEX) is one of India\'s premier agricultural commodity exchanges, providing a transparent, efficient, and secure marketplace for trading agricultural commodities. Regulated by the Securities and Exchange Board of India (SEBI), the exchange offers futures and options contracts across a wide range of commodities, including grains, oilseeds, pulses, and spices. NCDEX plays a vital role in enabling effective price discovery and risk management, benefiting farmers, traders, processors, and other participants in the agricultural ecosystem. The exchange also focuses on enhancing financial literacy and fostering greater participation from rural communities. Backed by a robust technology platform and efficient clearing and settlement systems, NCDEX contributes significantly to improving market efficiency, transparency, and the overall development of India\'s agricultural commodity markets.', '6', '2026-07-25 05:18:36', '2026-07-25 05:21:16', '5', '4', '1000', 'No', 'Both', 'Yes', 'unlisted', 'No'],
        [100019, 'Power Exchange India Limited - PXIL', 'power-exchange-india-limited-pxil', 'images/company-logo/power-exchange-india-limited-pxil.png', 157, 'Finance - Others', 'INE03N601010', 'PXIL', null, null, 'pre_ipo', null, '2008', '1', null, null, null, null, null, null, null, null, 'https://powerexindia.in/', null, 'Power Exchange India Limited (PXIL), established in 2008, is India\'s first institutionally promoted power exchange. It was jointly promoted by the National Stock Exchange (NSE), NCDEX, and leading power sector organizations, including Power Finance Corporation, state utilities, JSW Energy, GMR, and Tata Power Trading. Headquartered in Mumbai with an office in Delhi, PXIL offers a secure, fully automated, and technology-driven platform for the trading of electricity and related market products.

Operating under the regulatory oversight of the Central Electricity Regulatory Commission (CERC), PXIL enables trading across multiple market segments, including the Day-Ahead Market, Term-Ahead Market, Renewable Energy Certificates (RECs), and Energy Saving Certificates (ESCerts). The exchange provides comprehensive services ranging from participant registration and trading to clearing and settlement. By promoting transparent price discovery, efficient market operations, and innovative products such as green energy trading solutions, PXIL plays a key role in strengthening India\'s power markets, improving market liquidity, and supporting the nation\'s transition toward a sustainable and renewable energy future.', '6', '2026-07-25 07:42:08', '2026-07-25 07:43:46', '5', '4', '1000', 'No', 'NSDL', 'Yes', 'unlisted', 'No'],
        [100020, 'LAVA International Limited', 'lava-international-limited', 'images/company-logo/lava-international-limited.jpg', 31, 'Consumer Durables - Electronics', 'INE745X01022', 'Lava', null, null, 'pre_ipo', 'March', '2009', '1', null, null, null, null, null, null, null, null, 'https://www.lavamobiles.com/', null, 'Lava International Limited is a leading Indian multinational consumer electronics company specializing in the design, manufacturing, and distribution of mobile devices and related products. Incorporated on March 27, 2009, the company was founded by Hari Om Rai, Vishal Sehgal, Shailendra Nath Rai, and Sunil Bhalla as an extension of their telecommunications venture. Its product portfolio includes smartphones, feature phones, tablets, and other digital devices.

Headquartered in Noida, India, Lava has established a presence across multiple international markets, including Nepal, Bangladesh, Thailand, Indonesia, Mexico, Sri Lanka, and several countries in the Middle East. The company has developed strong in-house capabilities in industrial, mechanical, hardware, and software design, enabling it to independently design and manufacture its products. Recognized as one of the pioneers of the "Design in India" and "Make in India" initiatives, Lava maintains end-to-end control over product development and manufacturing within India. Through continuous innovation, customer-centric solutions, and a growing global footprint, the company continues to strengthen its position in the mobile handset industry.', '6', '2026-07-25 07:50:57', '2026-08-04 05:52:22', '5', '4', '500', 'No', 'Both', 'Yes', 'unlisted', 'No'],
        [100021, 'Transline Technologies Ltd', 'transline-technologies-ltd', 'images/company-logo/transline-technologies-ltd.png', 65, 'IT - Software', 'INE0OR401022', 'Transline Tech', null, null, 'pre_ipo', null, '2001', '1', null, null, null, null, null, null, null, null, 'https://translineindia.com/', null, 'Transline Technologies Limited is a New Delhi-based technology solutions company established in 2001, specializing in AI-powered security, surveillance, biometrics, and IT infrastructure solutions. Its offerings include video surveillance, AI-driven video analytics, smart-city and IoT solutions, biometric systems, e-surveillance, and IT infrastructure services. The company also develops proprietary products such as StorePulse, CamStore, CheckCam, and IDOne, alongside project management, support, and managed services.

Transline serves a diverse clientele across government, banking & finance, industrial infrastructure, healthcare, retail, education, corporate real estate, and transportation. Its business model combines system-integration projects, hardware/software sales, SaaS products, and maintenance services. The company highlights its 25+ years of operating experience, in-house R&D capabilities, diversified customer base, and multiple ISO/CMMI certifications.', '6', '2026-08-10 10:32:49', '2026-08-10 10:37:32', '4', '4', '500', 'No', 'Both', 'Yes', 'unlisted', 'No'],
    ];

    public function run(): void
    {
        $rows = array_map(fn (array $r) => array_combine(self::COLUMNS, $r), self::ROWS);

        foreach (array_chunk($rows, 100) as $chunk) {
            DB::table('unlisted_stocks')->upsert(
                $chunk,
                ['UL_STOCKS_FINCODE'],
                ['UL_STOCKS_COMPNAME', 'UL_STOCKS_SLUG', 'UL_STOCKS_LOGO_LINK', 'UL_STOCKS_IND_CODE', 'UL_STOCKS_INDUSTRY', 'UL_STOCKS_ISIN', 'UL_STOCKS_S_NAME', 'UL_STOCKS_CHAIRMAN', 'UL_STOCKS_MDIR', 'UL_STOCKS_CATEGORY', 'UL_STOCKS_INC_MONTH', 'UL_STOCKS_INC_YEAR', 'UL_STOCKS_STATUS', 'UL_STOCKS_ADD1', 'UL_STOCKS_ADD2', 'UL_STOCKS_ADD3', 'UL_STOCKS_CITY_NAME', 'UL_STOCKS_PINCODE', 'UL_STOCKS_STATE_NAME', 'UL_STOCKS_PHONE', 'UL_STOCKS_FAX_NO', 'UL_STOCKS_WEBSITE', 'UL_STOCKS_E_MAIL', 'UL_STOCKS_ABOUT', 'UL_STOCKS_INSERT_BY', 'UL_STOCKS_INSERT_TIME', 'UL_STOCKS_UPDATE_TIME', 'UL_STOCKS_COMP_RATING', 'UL_STOCKS_VALUATION_RATING', 'UL_STOCKS_LOT_SIZE', 'UL_STOCKS_ROFR_FLAG', 'UL_STOCKS_DEMAT_ACCOUNT_REQ', 'UL_STOCKS_BUY_SELL_FLAG', 'UL_STOCKS_COMPNAME_TYPE', 'UL_STOCKS_Qtr_Data_Publish']
            );
        }
    }
}
